insert into oneend.root_auth (root_auth_seq, root_auth_content, root_auth_date, root_auth_modify_date, root_auth_title, root_root_seq, user_id_user_seq) values (1, '아침에 해장국먹고 후식으로 카페디모라 방문했습니다!<br/>딸기케익이 너무 맛있더라고요ㅠㅠ<br/>그리고 저녁에는 등촌을 다녀왔는데 샤브샤브에 칼국수까지... 아주 만족한 하루였습니다.', '2025-03-20 22:25:34.216377', null, '김포 장기 방문', 1, 4);
insert into oneend.root_auth (root_auth_seq, root_auth_content, root_auth_date, root_auth_modify_date, root_auth_title, root_root_seq, user_id_user_seq) values (2, '빈대떡에서 소주 한 잔하고 친구들이랑 하이오커피도 다녀왔습니다!<br/>전이 너무 일품! 검단사거리 맛집으로도 유명하더라고요<br/>나중에 재방문 의사있고, 이번주에 못 가본 품육하고 해장국집도 가볼려고 합니다!', '2025-03-20 22:28:32.132401', null, '검단 다녀왔습니다!', 3, 4);
insert into oneend.root_auth (root_auth_seq, root_auth_content, root_auth_date, root_auth_modify_date, root_auth_title, root_root_seq, user_id_user_seq) values (3, '꽤 괜찮았습니다 ㅎㅎ', '2025-03-20 22:30:36.957221', '2025-03-21 01:59:01.640901', '검단 친척집 방문 김에 다녀왔어요', 3, 6);
insert into oneend.root_auth (root_auth_seq, root_auth_content, root_auth_date, root_auth_modify_date, root_auth_title, root_root_seq, user_id_user_seq) values (5, '등록해주신 루트를 보고 덕분에 장기동에 이사와서 맛집을 찾았습니다!<br/>다음에 또 가볼려고요', '2025-03-21 08:56:18.246438', null, '인증합니다!!', 1, 3);
insert into oneend.root_auth (root_auth_seq, root_auth_content, root_auth_date, root_auth_modify_date, root_auth_title, root_root_seq, user_id_user_seq) values (6, '좋았다!', '2025-03-21 08:59:26.596389', null, '방문', 1, 7);
insert into oneend.root_auth (root_auth_seq, root_auth_content, root_auth_date, root_auth_modify_date, root_auth_title, root_root_seq, user_id_user_seq) values (7, '알찼다~~', '2025-03-21 08:59:51.320350', null, '인중이요~~~', 3, 7);
insert into oneend.root_auth (root_auth_seq, root_auth_content, root_auth_date, root_auth_modify_date, root_auth_title, root_root_seq, user_id_user_seq) values (8, '뭉텅갔는데 고기가 너무 좋더라고요!<br/>덕분에 맛있게 먹었습니다', '2025-03-21 09:02:15.334354', null, '장기동 한식집 뿌시기', 1, 6);
insert into oneend.root_auth (root_auth_seq, root_auth_content, root_auth_date, root_auth_modify_date, root_auth_title, root_root_seq, user_id_user_seq) values (9, '빈대떡이 맛있더라고요 올려주신 루트로 가볼려다가 아쉽게도 가보지 못했습니다ㅠㅠ', '2025-03-21 09:02:55.855585', null, '검단 인증', 3, 6);
insert into oneend.root_auth (root_auth_seq, root_auth_content, root_auth_date, root_auth_modify_date, root_auth_title, root_root_seq, user_id_user_seq) values (10, 'ㅎㅎㅎㅎ 다음에 서울쪽도 부탁드려요~', '2025-03-21 09:03:37.804346', null, '인증합니답', 1, 6);
insert into oneend.root_auth (root_auth_seq, root_auth_content, root_auth_date, root_auth_modify_date, root_auth_title, root_root_seq, user_id_user_seq) values (11, 'ㅎㅎㅎㅎ', '2025-03-21 09:03:54.547145', null, '장기동 인증', 1, 6);
insert into oneend.root_auth (root_auth_seq, root_auth_content, root_auth_date, root_auth_modify_date, root_auth_title, root_root_seq, user_id_user_seq) values (12, '인증합니다!!!', '2025-03-21 12:06:11.694094', null, '검단 사거리', 3, 5);
insert into oneend.root_auth (root_auth_seq, root_auth_content, root_auth_date, root_auth_modify_date, root_auth_title, root_root_seq, user_id_user_seq) values (13, 'gggg', '2025-06-18 10:57:08.643066', null, 'ggg', 1, 4);
